server: 
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://dpg-d19focripnbc73eiqdkg-a.oregon-postgres.render.com:5432/tudoemaisdb_64ax
        username: tudoemaisdb_64ax_user
        password: yvaNUgMUs84QDenLm9AiQaFLf0RDhR54
        driver-class-name: org.postgresql.Driver
        initialize: true
    
    jpa:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            ddl-auto: update
            generate-ddl: true
        
    sql:
        init:
            schema-locations: classpath:/schema-postgresql.sql
            mode: always
            platform: postgres 