server: 
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://dpg-d19ehkili9vc739vnmg0-a.oregon-postgres.render.com:5432/tudoemaisdb_5cdt
        username:  tudoemaisdb_5cdt_user
        password: TlI1X7zKBKSaK9ACNBwNt0h0DErexZ0o
        driver-class-name: org.postgresql.Driver
        initialize: true
    
    jpa:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            ddl-auto: update
            generate-ddl: true
        
    sql:
        init:
            schema-locations: classpath:/schema-postgresql.sql
            mode: always
            platform: postgres 